# Generated by Django 2.2.28 on 2023-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatorApp', '0002_auto_20230731_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
