# Generated by Django 2.2.28 on 2023-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatorApp', '0003_auto_20230731_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
